spring:
  main:
    allow-bean-definition-overriding: true
telegram:
  filter:
    by-user-id:
      enabled: true
      whitelist:
        user-id: 123
  channel:
    id: 456
  api:
    file-uri: https://api.telegram.org/file/bot789/%s
  rate-limit:
    threshold: 1
    refresh-period: 1m
